import tkinter
from tkinter import *
from tkinter import ttk
from tkinter import messagebox
import mysql.connector as mysql
from PIL import ImageTk,Image
import time
from datetime import date
root=Tk()
root.geometry("1200x800")
root.title("Trex Gym System")
bg=ImageTk.PhotoImage(Image.open(r"C:\Users\RAHUL PATIL\OneDrive\Desktop\\ns.jpg"))
bg1=ImageTk.PhotoImage(Image.open(r"C:\Users\RAHUL PATIL\OneDrive\Desktop\\nw.jpg"))
root.iconphoto(True,bg1)
l=Label(root,image=bg)
l.place(x=0,y=0,relwidth=1,relheight=1)
l1=Label(root,text="$ ---  TREX  FITNESS  CLUB  --- $",font="ALGERIAN 25 underline ",bg="black",fg="red")
l1.place(x=500,y=70)
l2=Label(root,text="WELCOME  TO",font="ALGERIAN 25 underline",bg="black",fg="red")

l2.place(x=640,y=10)
def tick():
    tim=time.strftime("%H : %M : %S  %p  %a")
    cl.config(text=tim)
    cl.after(200,tick)

cl=Label(root,font="ALGERIAN 20",bg="black",fg="cyan")
cl.place(x=150,y=30)
c1=Label(root,text="Time :-",font="ALGERIAN 19",bg="black",fg="gold")
c1.place(x=71,y=32)
tick()
today=date.today()
c2=Label(root,text=today,font="ALGERIAN 17",bg="black",fg="cyan")
c2.place(x=150,y=80)
c3=Label(root,text="Date :-",font="ALGERIAN 17",bg="black",fg="gold")
c3.place(x=68,y=78)
def addnw():
    def subfunc():

        mid=eid.get()
        fn=ename.get()
        ln=elname.get()
        cn=enum.get()
        mail=e_email.get()
        add=eaddress.get(1.0, END)
        cal=edt.get()
        str=r1.get()
        am=int(at.get())
        sp=None
        ap=None
        sq=mysql.connect(user="root", password="root", host="127.0.0.1", database="gym")
        cur=sq.cursor()
        cur.execute("insert into data values (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",(mid,fn,ln,cn,mail,add,cal,str,am,sp,ap))
        sq.commit()
        messagebox.showinfo("done","data inserted successfully")
        sq.close()
    def cr():
        eid.delete(0,END)
        ename.delete(0,END)
        elname.delete(0,END)
        enum.delete(0,END)
        e_email.delete(0,END)
        eaddress.delete(1.0,END)
        edt.delete(0,END)
        at.delete(0,END)

###################################
    new=Tk()
    new.geometry("1200x800")
    new.title("new register")
    new.config(bg="yellow")
    lb = Frame(new, height=500, width=600,bg="spring green", highlightbackground="black", highlightthickness=9)
    lb.grid(row=0, column=0, padx=300, pady=100)
    ll=Label(new,text="! New  Register !",font="ALGERIAN 19",bg="yellow",fg="blue")
    ll.place(x=500,y=50)
    id =Label(lb, text="ID :",bg="spring green",font="ALGERIAN 9 underline")
    id.place(x=150,y=10)
    eid = Entry(lb,bg="light sky blue")
    eid.place(x=200,y=10, width=200)
    fname = Label(lb, text="First Name :",bg="spring green",font="ALGERIAN 9 underline")
    fname.place(x=110, y=40)
    ename = Entry(lb,bg="light sky blue",bd=2)
    ename.place(x=200, y=40, width=200)

    lname = Label(lb, text="Last Name :",bg="spring green",font="ALGERIAN 9 underline")
    lname.place(x=110, y=70)
    elname = Entry(lb,bg="light sky blue",bd=2)
    elname.place(x=200, y=70, width=200)

    cnum = Label(lb, text="Contact NO :",bg="spring green",font="ALGERIAN 9 underline")
    cnum.place(x=110, y=100)
    enum = Entry(lb,bg="light sky blue",bd=2)
    enum.place(x=200, y=100, width=200)
    email = Label(lb, text="Email Id :",bg="spring green",font="ALGERIAN 9 underline")
    email.place(x=110, y=140)
    e_email = Entry(lb,bg="light sky blue",bd=2)
    e_email.place(x=200, y=140, width=200)

    address = Label(lb, text="address :",bg="spring green",font="ALGERIAN 9 underline")
    address.place(x=110, y=170)
    eaddress = Text(lb,bg="light sky blue",bd=2)
    eaddress.place(x=200, y=170, width=200, height=90)

    dt = Label(lb, text="Date of joining: ",bg="spring green",font="ALGERIAN 9 underline")
    dt.place(x=90, y=270)
    edt = Entry(lb,bg="light sky blue",bd=2)
    edt.place(x=200, y=270,width=200)

    gender=Label(lb, text="gender :",bg="spring green",font="ALGERIAN 9 underline")
    gender.place(x=110, y=310)
    n=StringVar()
    r1 = ttk.Combobox(lb, width=20, font="ALGERIAN 11", textvariable=n, state="readonly")
    r1['values']=("Male","Female")
    r1.current()
    r1.place(x=190, y=310)


    amt = Label(lb, text="Amount :",bg="spring green",font="ALGERIAN 9 underline")
    amt.place(x=110, y=350)
    eamt = Label(lb, text="RS.",bg="spring green",font="ALGERIAN 9")
    eamt.place(x=190, y=350, width=20)
    at = Entry(lb,bg="light sky blue",bd=2)
    at.place(x=220, y=350)

    bt = Button(lb, text="SUBMIT", command=subfunc,fg="red",bg="yellow",font="ALGERIAN 9",bd=5)
    bt.place(x=150, y=410)
    bt1 = Button(lb, text="ClEAR", command=cr, fg="red", bg="yellow", font="ALGERIAN 9",bd=5)
    bt1.place(x=230, y=410)
    new.mainloop()
def showpec(id,fname,lname,phoneno,email,address,date,gender,amount,suppliment,workout):
    sq = mysql.connect(user="root", password="root", host="127.0.0.1", database="gym")
    cur = sq.cursor()
    cur.execute("select *from data where id=%s",(id,))
    data = cur.fetchone()
    fname.delete(0, END)
    lname.delete(0, END)
    phoneno.delete(0, END)
    email.delete(0, END)
    address.delete(0, END)
    date.delete(0, END)
    gender.delete(0, END)
    amount.delete(0, END)
    suppliment.delete(0,END)
    workout.delete(0,END)
    #####################################
    fname.insert(0, data[1])
    lname.insert(0, data[2])
    phoneno.insert(0, data[3])
    email.insert(0, data[4])
    address.insert(0, data[5])
    date.insert(0, data[6])
    gender.insert(0, data[7])
    amount.insert(0, data[8])
    suppliment.insert(0,data[9])
    workout.insert(0,data[10])


def updc(mid,fn,ln,cn,mail,add,cal,str,am):
    sq = mysql.connect(user="root", password="root", host="127.0.0.1", database="gym")
    cur = sq.cursor()
    cur.execute("update data set fname=%s, lname=%s, phoneno=%s, email=%s, address=%s, date=%s, gender=%s, amount=%s where id=%s",(mid,fn,ln,cn,mail,add,cal,str,am))
    sq.commit()
    messagebox.showinfo("done","Updated")
    exit()
    sq.close()
def deletefunc():
    def delfunc(id):
        sq = mysql.connect(user="root", password="root", host="127.0.0.1", database="gym")
        cur = sq.cursor()
        cur.execute("DELETE from data where id=%s",(id,))
        messagebox.showinfo("done", "Id deleted succesfully")
        sq.commit()
        exit()
        sq.close()
    #########################
    rt = Tk()
    rt.geometry("400x500")
    rt.config(bg="cyan")
    rt.title("delete")
    l=Label(rt, text=" id:",bg="cyan",font="ALGERIAN 10")
    l.place(x=100,y=70)
    e=Entry(rt,bg="yellow")
    e.place(x=150,y=70)
    b3 = Button(rt, text="delete",command=lambda: delfunc(e.get()),fg="blue",bg="white",font="ALGERIAN 10")
    b3.place(x=200,y=150)
    rt.mainloop()

def sup():
    def add():
        c=list.get()
        d=e_id.get()

        sq = mysql.connect(user="root", password="root", host="127.0.0.1", database="gym")
        cur = sq.cursor()
        cur.execute("update data set suppliment=%s where id=%s",(c,d))
        sq.commit()
        messagebox.showinfo("Thank u","suppliment added to customer succesfully")
        sq.close()
        exit()
    #################################
    sp=Tk()
    sp.geometry("1200x800")
    sp.title("suppliments")
    sp.config(bg="cyan")
    ll = Label(sp, text="!   Suppliment   !", font="ALGERIAN 19", bg="cyan", fg="red")
    ll.place(x=540, y=50)
    lg = Frame(sp, height=500, width=700, bg="orange", highlightbackground="blue", highlightthickness=9)
    lg.grid(row=0, column=0, padx=300, pady=100)
    id=Label(lg,text="enter id :",bg="orange",font="ALGERIAN 11")
    id.place(x=50,y=40)
    e_id=Entry(lg)
    e_id.place(x=130,y=40)
    su=Label(lg,text="suppliement :",bg="orange",font="ALGERIAN 11")
    su.place(x=30,y=90)
    n=tkinter.StringVar()
    list=ttk.Combobox(lg,width=50,font="ALGERIAN 11",textvariable=n,state="readonly")
    list.place(x=150,y=90)
    list['values']=("Whey Protein Supplement--Rs.350", "Glutamine Supplement--Rs.350","HMB Supplement--Rs.350", "Nitric Oxide Boosters Supplement--Rs.350",
            "Creatine Supplement--Rs.350","ZMA Supplement--Rs.350", "Vitamin C Supplement--Rs.350", "Weight Gainer Supplement--Rs.350")
    list.current()
    b2=Button(lg,text="add",command=add,bg="cyan",font="ALGERIAN 11")
    b2.place(x=120,y=220)
    sp.mainloop()
def pay():
    def show(id,amount,suppliment):
        x=eid1.get()
        y=epa.get()
        sq = mysql.connect(user="root", password="root", host="127.0.0.1",database="gym")
        cur = sq.cursor()
        cur.execute("select amount,suppliment from data where id=%s",(x,))
        data=cur.fetchone()
        amount.insert(0,data[0])
        suppliment.insert(0,data[1])
        sq.commit()
        sq.close()
    def up():
        x=epa.get()
        y=eid1.get()
        sq = mysql.connect(user="root", password="root", host="127.0.0.1", database="gym")
        cur = sq.cursor()
        cur.execute("update data set amount=%s where id=%s",(x,y))
        sq.commit()
        messagebox.showinfo("done","payment updated")
        exit()
        sq.close()
    def clr():
        esu.delete(0, END)
        epa.delete(0, END)
    ####################################################
    py=Tk()
    py.geometry("800x500")
    py.config(bg="yellow")
    py.title("payment status")
    ll = Label(py, text="!   payment   !", font="ALGERIAN 19", bg="yellow", fg="red")
    ll.place(x=540, y=50)
    lg = Frame(py, height=500, width=600, bg="orange", highlightbackground="cyan", highlightthickness=9)
    lg.grid(row=0,column=0, padx=300, pady=100)
    id1=Label(lg,text="id :",bg="orange",font="ALGERIAN 12")
    id1.place(x=70,y=30)
    eid1=Entry(lg,bg="light blue",width=30,bd=5)
    eid1.place(x=150,y=30)
    b7=Button(lg,text="Show",command=lambda :show(eid1.get(),epa,esu),fg="red",font="ALGERIAN 11",bd=5)
    b7.place(x=200,y=70)
    pa=Label(lg,text="paid amount: ",bg="orange",font="ALGERIAN 12")
    pa.place(x=30,y=110)
    epa=Entry(lg,bg="light blue",width=30,bd=5)
    epa.place(x=150,y=110)
    su = Label(lg, text="suppliment: ", bg="orange",font="ALGERIAN 12")
    su.place(x=30,y=170)
    esu=Entry(lg,bg="light blue",width=30,bd=5)
    esu.place(x=150,y=170)
    bz=Button(lg,text="update",command=up,fg="red",font="ALGERIAN 11",bd=5)
    bz.place(x=120,y=220)
    bn=Button(lg,text="Clear",command=clr,fg="red",font="ALGERIAN 11",bd=5)
    bn.place(x=220,y=220)
    py.mainloop()
def work():
    def done():
        a=el1.get()
        la=lt.get()
        sq = mysql.connect(user="root", password="root", host="127.0.0.1", database="gym")
        cur = sq.cursor()
        cur.execute("update data set workout=%s where id=%s",(la,a))
        sq.commit()
        messagebox.showinfo("done","workout detail updated successfully")
        exit()
        sq.close()
    ####################################################
    wk=Tk()
    wk.geometry("1200x800")
    wk.config(bg="grey")
    wk.title("workout status")
    ll = Label(wk, text="!   WorkOut   !", font="ALGERIAN 19", bg="grey", fg="red")
    ll.place(x=540, y=50)
    lg=Frame(wk,height=500, width=600,bg="orange", highlightbackground="blue", highlightthickness=9)
    lg.grid(row=0,column=0, padx=300, pady=100)
    l1=Label(lg,text="Enter id  :",bg="orange",fg="red",font="ALGERIAN 12")
    l1.place(x=50,y=40)
    el1=Entry(lg,bd=5)
    el1.place(x=150,y=40)
    li=Label(lg,text="workout done : ",bg="orange",fg="red",font="ALGERIAN 12")
    li.place(x=10,y=90)
    n=tkinter.StringVar()
    lt=ttk.Combobox(lg,width=40,font="ALGERIAN 12",textvariable=n,state="readonly")
    lt.place(x=150,y=90)
    lt['values']=("Wide Row","Bent Over Row","Kneeling One Arm Row","One Arm Row","Dead Lift","Stiff Legged Dead Lift","Bend to Opposite Foot"
                                    ,"Twisting Bend to Opposite Foot","Back Fly","squats","Push-ups","crunches","Bent-over-Row","Back & Shoulder","Chest & Triceps")
    bt=Button(lg,text="Workout-Done",command=done,font="ALGERIAN 12",bg="white")
    bt.place(x=100,y=150)

    wk.mainloop()

def Exit():
    ext=messagebox.askokcancel("Do u want exit","Do u want to exit??")
    if ext==True:
        exit()

def detail():
    nw=Tk()
    nw.geometry("800x500")
    nw.config(bg="deep sky blue")
    eid=Label(nw,text="ID :",bg="deep sky blue",font="ALGERIAN 9")
    eid.grid(row=0,column=0)
    new_eid=Entry(nw,bg="yellow")
    new_eid.grid(row=0,column=1)
    up_btn = Button(nw, text="show",font="ALGERIAN 9",command=lambda :showpec(new_eid.get(),new_ename,new_elname,nenum,ne_email,ne_add,ne_dt,ne_gn,ne_at,ne_sp,ne_ap))
    up_btn.grid(row=1,column=0)
    new_fname = Label(nw, text="First Name : ",bg="deep sky blue",font="ALGERIAN 9")
    new_fname.grid(row=2, column=0, sticky=W)
    new_ename = Entry(nw,bg="yellow")
    new_ename.grid(row=2, column=1)

    new_lname = Label(nw, text="Last Name : ",bg="deep sky blue",font="ALGERIAN 9")
    new_lname.grid(row=3, column=0, sticky=W)
    new_elname = Entry(nw,bg="yellow")
    new_elname.grid(row=3, column=1)
    ncnum = Label(nw, text="Contact NO :",bg="deep sky blue",font="ALGERIAN 9")
    ncnum.grid(row=4, column=0)
    nenum = Entry(nw,bg="yellow")
    nenum.grid(row=4, column=1)

    nemail = Label(nw, text="Email Id :",bg="deep sky blue",font="ALGERIAN 9")
    nemail.grid(row=5, column=0)
    ne_email = Entry(nw,bg="yellow")
    ne_email.grid(row=5, column=1)

    nadd = Label(nw, text="address :",bg="deep sky blue",font="ALGERIAN 9")
    nadd.grid(row=6, column=0)
    ne_add = Entry(nw,bg="yellow")
    ne_add.grid(row=6, column=1)
    ndt = Label(nw, text="date  :",bg="deep sky blue",font="ALGERIAN 9")
    ndt.grid(row=7, column=0)
    ne_dt = Entry(nw,bg="yellow")
    ne_dt.grid(row=7, column=1)
    ngn = Label(nw, text="gender :",bg="deep sky blue",font="ALGERIAN 9")
    ngn.grid(row=8, column=0)
    ne_gn = Entry(nw,bg="yellow")
    ne_gn.grid(row=8, column=1)
    nat = Label(nw, text="amount :",bg="deep sky blue",font="ALGERIAN 9")
    nat.grid(row=9, column=0)
    ne_at = Entry(nw,bg="yellow")
    ne_at.grid(row=9, column=1)
    nsp = Label(nw, text="suppliment :",bg="deep sky blue",font="ALGERIAN 9")
    nsp.grid(row=10, column=0)
    ne_sp = Entry(nw,bg="yellow")
    ne_sp.grid(row=10, column=1)
    nap = Label(nw, text="work out :", bg="deep sky blue",font="ALGERIAN 9")
    nap.grid(row=11, column=0)
    ne_ap = Entry(nw, bg="yellow")
    ne_ap.grid(row=11, column=1)
    b2=Button(nw,text="Update",command=lambda :updc(new_ename.get(),new_elname.get(),nenum.get(),ne_email.get(),ne_add.get(),ne_dt.get(),ne_gn.get(),ne_at.get(),new_eid.get()),font="ALGERIAN 9")
    b2.place(x=150,y=290)
    b=Button(nw, text="delete",command=deletefunc,font="ALGERIAN 9")
    b.place(x=210,y=290)
    nw.mainloop()
b=Button(root,text="addnewId",command=addnw,fg="black",font="ALGERIAN 14",bg="dark orange")
b.place(x=650,y=150,width=200,height=40)
b1=Button(root,text="customer-details",command=detail,fg="black",font="ALGERIAN 14",bg="dark orange")
b1.place(x=650,y=200,width=200,height=40)
b2=Button(root,text="Suppliements",command=sup,fg="black",font="ALGERIAN 14",bg="dark orange")
b2.place(x=650,y=250,width=200,height=40)
b6=Button(root,text="Payment",command=pay,fg="black",font="ALGERIAN 14",bg="dark orange")
b6.place(x=650,y=300,width=200,height=40)
b9=Button(root,text="Workout-checking",command=work,fg="black",font="ALGERIAN 14",bg="dark orange")
b9.place(x=650,y=350,width=200,height=40)
b10=Button(root,text="Exit",command=Exit,fg="black",font="ALGERIAN 14",bg="dark orange")
b10.place(x=650,y=400,width=200,height=40)
l2=Label(root,text="* ~ YEARLY  GYM  FEE  IS  RS.9000/- ~ *",bg="black",font="ALGERIAN 20 underline",fg="yellow")
l2.place(x=300,y=500)
l3=Label(root,text="* ~ ADDITIONAL  CHARGES  OF  ANY SUPPLIMENT  IS  RS.350/- ~ *",bg="black",font="ALGERIAN 20 underline",fg="yellow")
l3.place(x=510,y=600)

root.mainloop()